#!/bin/bash
i=1
while [ $i -lt 10 ]; do
    ./gen
    j=1
    while [ $j -lt 50 ]; do
	./ibe key_from_master_shares ben share
	echo Run $i.$j:
	echo Generating random ptext.old...
	dd if=/dev/urandom of=ptext.old bs=1 count=16384
	echo Encrypting and decrypting to ptext.new...
	cat ptext.old | ./ibe encrypt ben | ./ibe fixed_password_decrypt ben > ptext.new
	echo Looking for differences...
	diff ptext.old ptext.new
	j=$((j+1))
    done
    i=$((i+1))
done
